unique: unique.c table.c
	gcc -o unique unique.c table.c
bincount: bincount.c table.c
	gcc -o bincount bincount.c table.c
parity: parity.c table.c
	gcc -o parity parity.c table.c
clean: 
	rm -rf *.o unique bincount parity
