function [R9_decade,Vmeas_R9,Vmeas_R10,Vmeas_R1,Vmeas_R2,Vmeas_R3] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [R9_decade,Vmeas_R9,Vmeas_R10,Vmeas_R1,Vmeas_R2,Vmeas_R3] =
%   IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [R9_decade,Vmeas_R9,Vmeas_R10,Vmeas_R1,Vmeas_R2,Vmeas_R3] =
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [R9_decade,Vmeas_R9,Vmeas_R10,Vmeas_R1,Vmeas_R2,Vmeas_R3] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [R9_decade,Vmeas_R9,Vmeas_R10,Vmeas_R1,Vmeas_R2,Vmeas_R3] =
%   importfile('ELEN050L_Project_1_Measured_Results.xlsx','Sheet1',2,49);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/10/12 20:19:33

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 49;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
R9_decade = data(:,1);
Vmeas_R9 = data(:,2);
Vmeas_R10 = data(:,3);
Vmeas_R1 = data(:,4);
Vmeas_R2 = data(:,5);
Vmeas_R3 = data(:,6);

